// Writes docs/CODE_MAP.md: every source file with the comment at its top, grouped by folder.
// The comments are the source of truth; run `npm run code-map` after adding or renaming a file.
import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const SKIP = /\/(locales)\/|icons-extra\.js$/;
const GROUPS = [
  ['src', 'Core (state, connection, helpers)'],
  ['src/api', 'Moonraker client'],
  ['src/views', 'Pages'],
  ['src/components', 'Components and dashboard cards'],
  ['src/editor', 'Config editor (CodeMirror)'],
  ['src/demo', 'Live demo'],
];

function header(file) {
  let text = fs.readFileSync(file, 'utf8');
  if (file.endsWith('.vue')) text = text.replace(/^<script[^>]*>\n/, '');
  const out = [];
  for (const line of text.split('\n')) {
    const m = /^\/\/ ?(.*)$/.exec(line);
    if (!m) break;
    out.push(m[1]);
  }
  return out.join('\n').trim();
}

let md = '# Code map\n\nEvery source file and what it does, taken from the comment at the top of the file.\n';
md += 'Generated by `npm run code-map`, do not edit by hand.\n';
for (const [dir, title] of GROUPS) {
  const abs = path.join(ROOT, dir);
  const files = fs
    .readdirSync(abs)
    .filter((f) => /\.(js|vue)$/.test(f))
    .map((f) => path.join(abs, f))
    .filter((f) => !SKIP.test(f))
    .sort();
  if (!files.length) continue;
  md += `\n## ${title}\n\n`;
  for (const f of files) {
    const rel = path.relative(ROOT, f);
    const h = header(f) || '(no description yet)';
    const lines = h.split('\n');
    md += `**[${rel}](../${rel})**  \n${lines.map((l) => l.replace(/^ {2}- /, '- ')).join('  \n')}\n\n`;
  }
}
fs.writeFileSync(path.join(ROOT, 'docs/CODE_MAP.md'), md);
console.log('docs/CODE_MAP.md written');
